### ISSUE TITLE
Swift 2.0 support

### ISSUE THREAD

**Issue by thediary** [FahimF/FloatLabelFields#12]
Please add swift 2 support, possibly in a separate branch.

**Comment by Lawgrin** [comment]
Just add a gettext function that returns a non-nil string and then switch all your referances from textview.text? to textview.gettext()

**Comment by dms90** [comment]
+1 on @thediary request :). Are you planning to add Swift 2 support?

**Comment by meismyles** [comment]
I've updated the project for Swift 2.0. I've submitted a pull request but there hasn't been much activity by @FahimF for a little while so not sure whether it will be accepted anytime soon / if at all.

You can get it from my fork here though: https://github.com/meismyles/FloatLabelFields.

**Comment by FahimF** [comment]
Sorry about the disappearance :) The project has been updated for Swift 2.2 and a separate branch created for Swift 3.
