### ISSUE TITLE
UITextField round border style support

### ISSUE THREAD

**Issue by tbaranes** [FahimF/FloatLabelFields#8]
Isn't it possible to use a round border style with FloatLabelFields? That could be awesome

**Comment by lastMove** [comment]
It is actually supported, By exemple in storyboard select a FloatLabelFields. In the rightPanel select the "Attributes Inspector" the 4th one. In the TextField section you will find "Border Style". 
Hope it helps :)

**Comment by tbaranes** [comment]
That's what I thought too, but even after trying in my project, or in your sample, it's not working. Each time I set the `UITextFieldBorderStyle` to the round one, it's not keeping its state and going back to the rect style.

Did I miss something else?

**Comment by haydarKarkin** [comment]
Hello,

I'm here because of same reason. How can I solve this issue?

**Comment by Lawgrin** [comment]
The why i solved this was to do the following. Note i dove head first and didn't RTFM so if there is a simpler way rather use that

in the setup() function replace
borderStyle = UITextBorderStyle.None
with 
if borderStyle != UITextBorderStyle.None
        {
            layer.borderColor = UIColor.blue.CGColor
            layer.borderWidth = 1.0
            layer.cornerRadius = 5
        }

then to fix the height issue (locked on 30)
ensure that you have some way to identify it (easier for this step) you can use placeholder text as an identifier
Right click on the storyboard select "open as" > "Source Code"
find you text look for the height attribute and set it to 55 seemed to work for me with my text size

Like i said try at own risk
